In [ ]:
# NumPY : Numerical Python (developed in 2005)

In [5]:
import numpy as np # as is alias

In [3]:
np.__version__

'2.4.4'

In [ ]:
#Numpy >> made using c so it is faster (most fast programming language is c++ and then c)
# Numpy >> if fastest >> due to array
# array>> stores homogenous data in conigious/continous memory location 

In [5]:
l = [1,2,3,4,4,5]

In [8]:
arr = np.array(l) # ndarray : n deminsional array

In [7]:
type(arr)

numpy.ndarray

In [ ]:
# numpy array >> desinged to store homogenous value of Integer, float , String

In [ ]:
l = [1,2,3,4,"Pavav"]
arr1 = np.array(l)
arr1
# since array stores only homogenous - it converted everything in string

array(['1', '2', '3', '4', 'Pavav'], dtype='<U21')

In [11]:
# finding Dimension of array >> np.ndim
np.ndim(arr1)

1

In [ ]:
arr = np.array([[1,2,3] ,[4,5,5]])

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 5]])

In [21]:
np.ndim(arr)

2

# This is 2-dimensional array
# But there is specialised 2-dimensional function array for this - np.matrix()

In [22]:
mat = np.matrix([1,2,3,4]) # specilisec 2 dimensional arry
mat

matrix([[1, 2, 3, 4]])

In [23]:
type(mat)

numpy.matrix

In [24]:
np.ndim(mat)

2

# To understand the dimension : see the no of opeining and closing square brackets
# [] -> 1 deminsioanl 
# [[]] -> 2 dimensional
# [[[]]] -> 3 dimensional

In [ ]:
np.matrix([[[1,2] ,[3,4] ,[5,6]]]) # will throw error : matrix is only 2 dimensional array

In [28]:
l = np.array([[[1,2] ,[3,4] ,[5,6]]]) # No error

In [29]:
np.ndim(l)

3

In [30]:
# another way to convert into array
l = [1,2,3,4]
np.asarray(l)

array([1, 2, 3, 4])

In [32]:
type(l) # note you have to store it 

list

In [33]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [43]:
# shallow copy >> shares common address 
a = np.array([1,2,3])
b = a

In [44]:
b[2] = 4

In [45]:
a

array([1, 2, 4])

In [47]:
# deep copy
b = np.copy(a)
b

array([1, 2, 4])

In [48]:
b[2] =3
a

array([1, 2, 4])

# To create an array >> np.array() , np.asarray() , np.asanyarray()

# Multiple approches to generate an array

In [ ]:
arr = np.fromfunction(lambda i,j : i==j, (3,3))  # (3,3) = no of rows and colums = 3
arr

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [53]:
np.shape(arr)

(3, 3)

In [54]:
np.size(arr)

9

In [52]:
arr1 = np.fromfunction(lambda i,j : i+j, (3,3))
arr1

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

# True is 1 and False is 0 in Python
# true - false = 1

In [55]:
arr2 = np.fromfunction( lambda i,j : i*j , (3,3))
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [58]:
for i in range(5) : 
    print(i)

0
1
2
3
4


In [60]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [63]:
(i for i in range(5))

<generator object <genexpr> at 0x000002810A3225A0>

In [62]:
type(np.array([i for i in range(5)]))

numpy.ndarray

In [3]:
# WE can convert a generator object to a Numpy Array using : np.fromiter(iterable) function
iterator = (i for i in range(5))
iterator

<generator object <genexpr> at 0x000002394090DA40>

In [ ]:
np.fromiter(iterator , int)  # it takes iterator object and convet it into an Numpy array

array([0, 1, 2, 3, 4])

In [ ]:
np.fromstring('12 22 33' , sep = ' ') # by default : float

array([12., 22., 33.])

In [9]:
np.fromstring('22 33 42' , sep = ' ' , dtype=int)

array([22, 33, 42])

In [13]:
# For string character : 
string = "pavan ,ajay ,vijay ,bijay"
string.split(",")

['pavan ', 'ajay ', 'vijay ', 'bijay']

In [ ]:
range(10) # genreator

range(0, 10)

In [15]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
# Numpy array it is directly 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [2]:
import numpy as np