In [1]:
import random

#  Random choice

In [ ]:
random.choice((1,2,3,4,5,)) # gives you random element

2

In [10]:
random.choice("Priya")

'P'

# Random Range (int)

In [13]:
random.randrange(1,10)

4

In [ ]:
random.randrange()

0

# Random (flaot)

In [23]:
random.random()

0.7139866518555597

# Shuffile List

In [28]:
lis = [1, 2, 3, 4, 5 , 6 , 7]
random.shuffle(lis)
lis

[1, 5, 4, 6, 2, 7, 3]

# Random in Numpy

In [3]:
import numpy as np

In [33]:
np.array([])

array([], dtype=float64)

# Random_sample : gives you only 1d random data

In [34]:
np.random.random_sample()

0.054949089604498624

In [36]:
np.random.random_sample(4,)

array([0.68380844, 0.59971288, 0.86739   , 0.6641567 ])

In [37]:
np.random.random_sample(4)

array([0.36438424, 0.13095989, 0.14976491, 0.0351149 ])

In [38]:
np.random.random_sample(4,5)

TypeError: random_sample() takes at most 1 positional argument (2 given)

# For 2d : 
# random.rand()
# random.randn()
# random.randint()

In [40]:
np.random.rand(2,3)

array([[0.26368406, 0.4300364 , 0.27352856],
       [0.92209958, 0.90891158, 0.2592158 ]])

In [41]:
np.random.rand(3,3)

array([[0.42380244, 0.37276681, 0.63767386],
       [0.27061561, 0.48752303, 0.15826359],
       [0.50025395, 0.12778159, 0.14010898]])

In [ ]:
np.random.randn(2,3) # standard normal distribution 

array([[ 1.38252305,  0.46688462, -0.05682946],
       [ 1.47388312,  1.04740126,  0.68978666]])

# Reshaping : same array just changing its shape
but size will be same

In [58]:
arr = np.random.randint(1,4,(3,4))
arr

array([[3, 1, 1, 1],
       [3, 1, 2, 3],
       [3, 1, 3, 1]], dtype=int32)

In [60]:
arr.shape

(3, 4)

In [61]:
arr.reshape(6,2)

array([[3, 1],
       [1, 1],
       [3, 1],
       [2, 3],
       [3, 1],
       [3, 1]], dtype=int32)

In [63]:
arr.reshape(12 ,1)

array([[3],
       [1],
       [1],
       [1],
       [3],
       [1],
       [2],
       [3],
       [3],
       [1],
       [3],
       [1]], dtype=int32)

In [ ]:
arr.reshape(-1,3) # use -1 in row/col in which we are not sure but we know any one thing atleast

array([[3, 1, 1],
       [1, 3, 1],
       [2, 3, 3],
       [1, 3, 1]], dtype=int32)

# Conditional on array

In [45]:
arr = np.random.randint(1,3, (3,4))
arr

array([[2, 1, 2, 2],
       [1, 2, 2, 2],
       [2, 1, 1, 1]], dtype=int32)

In [46]:
arr > 1

array([[ True, False,  True,  True],
       [False,  True,  True,  True],
       [ True, False, False, False]])

In [47]:
arr[arr >1]

array([2, 2, 2, 2, 2, 2, 2], dtype=int32)

# Slicing in the array

In [48]:
arr

array([[2, 1, 2, 2],
       [1, 2, 2, 2],
       [2, 1, 1, 1]], dtype=int32)

In [49]:
# 0 to 2nd row
arr[0:3]

array([[2, 1, 2, 2],
       [1, 2, 2, 2],
       [2, 1, 1, 1]], dtype=int32)

In [50]:
# 0 to 2nd row and 1 and 3 col
arr[0:3 ,[1,3]]

array([[1, 2],
       [2, 2],
       [1, 1]], dtype=int32)

In [51]:
# 0 to 2nd row and 1 to 3rd col
arr[0:3 , 1:4]

array([[1, 2, 2],
       [2, 2, 2],
       [1, 1, 1]], dtype=int32)

# Mathematical operation on the 2 array

In [4]:
arr1 = np.random.randint(1,3,(3,4))
arr2 = np.random.randint(1,3,(3,4))

In [53]:
arr1

array([[1, 2, 2, 2],
       [1, 1, 2, 2],
       [2, 2, 1, 2]], dtype=int32)

In [54]:
arr2

array([[1, 1, 1, 1],
       [2, 1, 2, 2],
       [1, 2, 2, 1]], dtype=int32)

In [55]:
arr1+arr2

array([[2, 3, 3, 3],
       [3, 2, 4, 4],
       [3, 4, 3, 3]], dtype=int32)

In [56]:
arr1 * arr1 # this is index wise multipication , not matrix mulitpication

array([[1, 4, 4, 4],
       [1, 1, 4, 4],
       [4, 4, 1, 4]], dtype=int32)

In [57]:
arr1 / arr2

array([[1. , 2. , 2. , 2. ],
       [0.5, 1. , 1. , 1. ],
       [2. , 1. , 0.5, 2. ]])

In [6]:
m1 = np.random.randint(1,3 ,(3,4))
m2 = np.random.randint(1,3 ,(4,2))

In [ ]:
m1 @ m2  # Matrix multipication

array([[5, 6],
       [7, 9],
       [8, 8]], dtype=int32)

In [8]:
m1.T

array([[1, 1, 1],
       [1, 2, 1],
       [1, 2, 2],
       [1, 1, 2]], dtype=int32)