In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,3, (3,4))
arr

array([[1, 2, 1, 2],
       [2, 2, 1, 2],
       [1, 2, 2, 1]], dtype=int32)

In [4]:
# flatten the array : converting to 1d array
arr.flatten()

array([1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1], dtype=int32)

# Expanding the array : increasing the dimension by 1 either in col=1/row=0 (axis)

In [5]:
arr

array([[1, 2, 1, 2],
       [2, 2, 1, 2],
       [1, 2, 2, 1]], dtype=int32)

In [6]:
arr.ndim

2

In [24]:
arr1 = np.expand_dims(arr, axis=1)

In [ ]:
arr1

array([[[2, 1, 1, 2]],

       [[2, 2, 1, 1]],

       [[1, 2, 2, 1]]], dtype=int32)

In [10]:
arr1.ndim

3

In [27]:
arr2 = np.expand_dims(arr, axis=1)
arr2

array([[[2, 1, 1, 2]],

       [[2, 2, 1, 1]],

       [[1, 2, 2, 1]]], dtype=int32)

# Squeezing the dimension

In [11]:
arr1

array([[[1, 2, 1, 2]],

       [[2, 2, 1, 2]],

       [[1, 2, 2, 1]]], dtype=int32)

In [12]:
np.squeeze(arr1)

array([[1, 2, 1, 2],
       [2, 2, 1, 2],
       [1, 2, 2, 1]], dtype=int32)

In [13]:
np.squeeze(arr1).ndim

2

# Repeating the array : repeat given no of times and returns you 1-D array

In [29]:
arr = np.array([1,2,3])

In [15]:
np.repeat(arr, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [30]:
arr = np.random.randint(1,3 , (3,4))
arr


array([[2, 1, 2, 1],
       [1, 2, 2, 2],
       [1, 2, 2, 2]], dtype=int32)

In [31]:
np.repeat(arr,2)

array([2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 2], dtype=int32)

# Repeating the array - Axis wise

In [22]:
a1 = np.random.randint(1,3 , (3,4))
a1


array([[2, 2, 2, 1],
       [1, 1, 2, 1],
       [2, 2, 2, 2]], dtype=int32)

In [21]:
np.repeat(a1 , 2, axis = 0)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [1, 2, 2, 1],
       [1, 2, 2, 1],
       [1, 1, 2, 1],
       [1, 1, 2, 1]], dtype=int32)

In [23]:
np.repeat(a1 , 2, axis = 1)

array([[2, 2, 2, 2, 2, 2, 1, 1],
       [1, 1, 1, 1, 2, 2, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2]], dtype=int32)

# Rolling

In [39]:
m = np.array([[1] , [2] , [3]])
m

array([[1],
       [2],
       [3]])

In [33]:
m.shape

(3, 1)

In [34]:
np.roll(m, -1)

array([[2],
       [3],
       [1]])

In [35]:
np.roll(m , -2)

array([[3],
       [1],
       [2]])

In [41]:
np.roll(m, 1)

array([[3],
       [1],
       [2]])

In [36]:
b = np.array([[1,2] , [3,4] , [5,6] ,[7,8]])
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
np.roll(b, -1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [42]:
new_arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.roll(new_arr , 1 , axis = 0) # last row rolled up to top

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [44]:
np.roll(new_arr , 1 , axis = 1) # last col rolled up to start

array([[3, 1, 2],
       [6, 4, 5],
       [9, 7, 8]])

# Mathematical Operation

In [55]:
arr = np.random.randint(1,3 ,(4,5))
arr

array([[2, 1, 2, 1, 1],
       [1, 1, 2, 2, 1],
       [1, 2, 2, 2, 1],
       [2, 1, 1, 2, 2]], dtype=int32)

In [46]:
np.sin(arr)

array([[0.90929743, 0.90929743, 0.90929743, 0.90929743, 0.90929743],
       [0.84147098, 0.90929743, 0.90929743, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.90929743, 0.84147098],
       [0.84147098, 0.90929743, 0.84147098, 0.84147098, 0.90929743]])

In [47]:
np.log10(arr)

array([[0.30103, 0.30103, 0.30103, 0.30103, 0.30103],
       [0.     , 0.30103, 0.30103, 0.     , 0.     ],
       [0.     , 0.     , 0.     , 0.30103, 0.     ],
       [0.     , 0.30103, 0.     , 0.     , 0.30103]])

In [53]:
np.pow(arr, 4)

array([[ 1,  1,  1,  1,  1],
       [16,  1,  1, 16,  1],
       [ 1, 16, 16, 16, 16],
       [ 1,  1,  1, 16,  1]], dtype=int32)

In [56]:
np.max(arr)

np.int32(2)

# Sorting and searching

In [57]:
np.sort(arr)

array([[1, 1, 1, 2, 2],
       [1, 1, 1, 2, 2],
       [1, 1, 2, 2, 2],
       [1, 1, 2, 2, 2]], dtype=int32)

In [67]:
p = np.random.random_sample(5)
p

array([0.18063965, 0.47157832, 0.15491053, 0.87952037, 0.63532399])

In [68]:
np.sort(p)

array([0.15491053, 0.18063965, 0.47157832, 0.63532399, 0.87952037])

In [71]:
np.searchsorted(p, 0.12223)

np.int64(0)